version: "3.8"

services:
  python:
    build:
      context: .
      dockerfile: docker/Dockerfile-python
    ports:
      - 5000:5000
    volumes:
      - .:/fhodot
    depends_on:
      - postgis
      - redis
  postgis:
    image: postgis/postgis:15-3.4
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: db
      POSTGRES_DB: gregrs_fhodot
  redis:
    image: redis:7.0.15-bookworm
  imposm:
    environment:
      PGHOST: postgis
      PGUSER: postgres
      PGPASSWORD: db
      PGDATABASE: gregrs_fhodot
    build:
      context: .
      dockerfile: docker/Dockerfile-imposm
    volumes:
      - .:/fhodot
    depends_on:
      - postgis
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile-node
    volumes:
      - .:/fhodot
    working_dir: /fhodot
    command: npm run watch
  rstats:
    build:
      context: .
      dockerfile: docker/Dockerfile-rstats
    volumes:
      - .:/fhodot
    depends_on:
      - postgis

volumes:
  db-data:
